<a href="https://colab.research.google.com/github/sagargahalod/Misc/blob/master/neural_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
input = np.arange(4,9)
bias = 2
weight = np.arange(3,8)


In [11]:
input,bias,weight

(array([4, 5, 6, 7, 8]), 2, array([3, 4, 5, 6, 7]))

In [12]:
neuron1 =((input[0]*weight[0])+(input[1]*weight[1])+(input[2]*weight[2])+(input[3]*weight[3])+(input[4]*weight[4])+bias)
neuron1

162

In [17]:
#multiple neurons in the layer 
input = np.arange(4,9)
bias1 = 2
bias2 = -4
bias3 = 8
weight1 = np.arange(3,8)
weight2 = np.arange(4,9)
weight3 = np.arange(2,7)


In [18]:
output = [(input[0]*weight1[0])+(input[1]*weight1[1])+(input[2]*weight1[2])+(input[3]*weight1[3])+(input[4]*weight1[4])+bias1,
          (input[0]*weight2[0])+(input[1]*weight2[1])+(input[2]*weight2[2])+(input[3]*weight2[3])+(input[4]*weight2[4])+bias2,
          (input[0]*weight3[0])+(input[1]*weight3[1])+(input[2]*weight3[2])+(input[3]*weight3[3])+(input[4]*weight3[4])+bias3]
          

In [19]:
output

[162, 186, 138]

In [27]:
input = np.arange(4,9)
bias = np.arange(1,4)
weights =[np.arange(3,8),np.arange(4,9),np.arange(2,7)]

# output for current layer
L_output = []

#Calculating output for each neuron
for i,j in zip(weights,bias):
  neuron_output = 0
  # For each input and weight to the neuron
  for k,l in zip(input,i):
    neuron_output += k*l   #neuron input * weight 
  # Add bias
  neuron_output += j
  # Put neuron’s result to the layer’s output list
  L_output.append(neuron_output)

print(L_output)


[161, 192, 133]


In [26]:
for i,j in zip(weights,bias):
  print (i,j)

[3 4 5 6 7] 1
[4 5 6 7 8] 2
[2 3 4 5 6] 3


In [28]:
a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]
dot_product = a[ 0 ] * b[ 0 ] + a[ 1 ] * b[ 1 ] + a[ 2 ] * b[ 2 ]
print (dot_product)

20


In [29]:
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , - 0.5 , 1.0 ]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print (outputs)

4.8


In [33]:
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [[ 0.2 , 0.8 , - 0.5 , 1 ],
           [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
           [ - 0.26 , - 0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]
# Order is changed first we are calculating the dot products between input and weights and then adding the corresponding biases
layer_outputs = np.dot(weights, inputs) + biases
print (layer_outputs)

[4.8   1.21  2.385]


As we can see, to perform a matrix product on two vectors, we took one as is, transforming it into
a row vector, and the second one using transposition on it to turn it into a column vector. That
allowed us to perform a matrix product that returned a matrix containing a single value

In [34]:
a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]
a = np.array([a])
b = np.array([b]).T
np.dot(a, b)

array([[20]])