<a href="https://colab.research.google.com/github/sagargahalod/Misc/blob/master/SVM_complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn import datasets

cancer = datasets.load_breast_cancer()

In [8]:
print('Features :',cancer.feature_names)

Features : ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [10]:
print('Target class :',cancer.target_names)

Target class : ['malignant' 'benign']


In [11]:
cancer.data.shape

(569, 30)

In [12]:
print(cancer.data[:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414

In [20]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(cancer.data,cancer.target,test_size=0.3,random_state=42)

In [21]:
from sklearn import  svm

model = svm.SVC(kernel = 'linear')

model.fit(X_train,y_train)

y_pred = model.predict(X_test)



In [45]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,classification_report 

print('Accuracy Score : ',accuracy_score(y_test,y_pred))



ValueError: ignored

In [30]:
print('Precision :',precision_score(y_test,y_pred))

print('Recall :',recall_score(y_test,y_pred))

print('\n Total Classification report: \n')

print(classification_report(y_test,y_pred))

Precision : 0.9636363636363636
Recall : 0.9814814814814815

 Total Classification report: 

              precision    recall  f1-score   support

           0       0.97      0.94      0.95        63
           1       0.96      0.98      0.97       108

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [31]:
# Tuning hyperparameter 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [35]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

iris = pd.read_csv(url,names=colnames)

In [41]:
X= iris.drop('Class',axis=1)
y = iris['Class']
print(X.shape,y.shape)

(150, 4) (150,)


In [42]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [44]:
polymodel = svm.SVC(kernel='poly',degree=4)
polymodel.fit(X_train,y_train)
y_pred1 = polymodel.predict(X_test)

print('Classification report',classification_report(y_test,y_pred1))

Classification report                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [46]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test,y_pred1))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [49]:
rbfmodel = svm.SVC(kernel='rbf')
rbfmodel.fit(X_train,y_train)
y_pred2 = rbfmodel.predict(X_test)


In [50]:
print(confusion_matrix(y_test,y_pred2))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [51]:
print('Classification report',classification_report(y_test,y_pred1))


Classification report                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

